version: '3.8'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
        - web
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

  web:
    image: httpd:alpine
    container_name: web
#    ports:
#      - '9001:80'
    volumes:
      - $PWD/htdocs/:/usr/local/apache2/htdocs/
    restart: on-failure
